### ISSUE TITLE
Unexpected token < while building from stateful lex file

### ISSUE THREAD

**Issue by danyaPostfactum** [zaach/jison-lex#1]
I'm just trying to build a lexer from documentation example:

```
%s expect

%%
expect-floats        this.begin('expect');

<expect>[0-9]+"."[0-9]+      {
            console.log( "found a float, = " + yytext );
            }
<expect>\n           %{
            /* that's the end of the line, so
             * we need another "expect-number"
             * before we'll recognize any more
             * numbers
             */
            this.begin('INITIAL');
            %}

[0-9]+      console.log( "found an integer, = " + yytext );

"."         console.log( "found a dot" );
```

and get `case 0:expect-floats         this.begin('expect')`

Ok, I deleted this line, but get:

```
undefined:5
case 0:<expect>[0-9]+"."[0-9]+      {
SyntaxError: Unexpected token <
```

**Comment by zaach** [comment]
I didn't encounter any errors, but I put quotes around `expect-floats` because it wasn't catching the dash. Here's the input/output: https://gist.github.com/4661245

**Comment by danyaPostfactum** [comment]
I have file test.jisonlex:

```
%s expect

%%
'expect-floats'        this.begin('expect');

<expect>[0-9]+"."[0-9]+      {
            console.log( "found a float, = " + yytext );
            }
<expect>\n           %{
            /* that's the end of the line, so
             * we need another "expect-number"
             * before we'll recognize any more
             * numbers
             */
            this.begin('INITIAL');
            %}

[0-9]+      console.log( "found an integer, = " + yytext );

"."         console.log( "found a dot" );
```

I run command:

```
>node_modules\.bin\jison-lex test.jisonlex -o out.js
```

and get:

```
undefined:5
case 0:'expect-floats'        this.begin('expect');
                              ^^^^
SyntaxError: Unexpected token this
    at Function (unknown source)
    at Object.buildActions (C:\Users\╨Ф╨░╨╜╨╕╨╗\Git\node_modules\jison-lex\regex
p-lexer.js:118:12)
    at Object.RegExpLexer (C:\Users\╨Ф╨░╨╜╨╕╨╗\Git\node_modules\jison-lex\regexp
-lexer.js:131:39)
    at processGrammar (C:\Users\╨Ф╨░╨╜╨╕╨╗\Git\node_modules\jison-lex\cli.js:70:
17)
    at Object.exports.main (C:\Users\╨Ф╨░╨╜╨╕╨╗\Git\node_modules\jison-lex\cli.j
s:44:56)
    at Object.<anonymous> (C:\Users\╨Ф╨░╨╜╨╕╨╗\Git\node_modules\jison-lex\cli.js
:88:13)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

I tried many times. Same problem with jison module when I use a separate lex file. There is no probjem when I combine lex file into grammar. I don't even know how to figure out the cause :(

**Comment by danyaPostfactum** [comment]
Just tested on Linux. Works fine. So, this is platform-depended issue. Bad news for Windows users :)

**Comment by danyaPostfactum** [comment]
Sorry. I think there was BOM-symbol in my lex file. I recreated file and now it works.
